#!/usr/bin/env python3
"""Materialize self-contained public Skills from the canonical DailyPaper suite."""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SUITE_ROOT = REPO_ROOT / "skills" / "daily-papers"
SKILLS_ROOT = REPO_ROOT / "skills"


@dataclass(frozen=True)
class PublicSkill:
    name: str
    description: str
    workflow: str
    resources: tuple[str, ...]


COMMON_CONFIG = (
    "scripts/shared/machine_config.py",
    "scripts/shared/user_config.py",
    "scripts/shared/user-config.json",
)
MOC_RESOURCES = (
    "scripts/shared/moc_builder.py",
    "scripts/shared/generate_concept_mocs.py",
    "scripts/shared/generate_paper_mocs.py",
)
CONFIG_GUARD = ("scripts/configure/config_manager.py",)

PUBLIC_SKILLS = (
    PublicSkill(
        name="paper-reader",
        description=(
            "Read, analyze, summarize, and save academic papers from arXiv, "
            "local PDF files, or explicit Zotero inputs into an Obsidian Vault. "
            "Use for paper reading, critical analysis, formula extraction, "
            "paper notes, Zotero collection reading, “读一下这篇论文”, "
            "“快速看一下这篇论文”, or “批判性分析这篇论文”."
        ),
        workflow="workflows/paper-reader.md",
        resources=COMMON_CONFIG
        + MOC_RESOURCES
        + CONFIG_GUARD
        + (
            "assets/paper-note-template.md",
            "references/paper-reader/concept-categories.md",
            "references/paper-reader/cv-dl-terminology.md",
            "references/paper-reader/image-troubleshooting.md",
            "references/paper-reader/quality-standards.md",
            "references/paper-reader/zotero-guide.md",
            "scripts/daily/download_note_images.py",
            "scripts/paper-reader/paper_daemon.py",
            "scripts/paper-reader/reorganize_notes.py",
            "scripts/paper-reader/zotero_helper.py",
        ),
    ),
    PublicSkill(
        name="generate-mocs",
        description=(
            "Regenerate deterministic Obsidian Map of Content pages for "
            "DailyPaper paper notes and concept notes. Use when the user asks "
            "to update indexes, refresh navigation pages, or rebuild MOCs after "
            "moving, adding, or renaming notes, including “更新索引”, "
            "“刷新论文目录”, and “更新 MOC”."
        ),
        workflow="workflows/generate-mocs.md",
        resources=COMMON_CONFIG + MOC_RESOURCES + CONFIG_GUARD,
    ),
    PublicSkill(
        name="configure-dailypaper",
        description=(
            "Perform first-run DailyPaper onboarding and safely inspect or "
            "update configuration. Use immediately after installation to set "
            "the per-machine Vault path, initialize or validate the fixed Vault "
            "repository, configure optional Zotero paths, or change research "
            "keywords, arXiv categories, thresholds, and index automation. Use "
            "for “配置每日论文”, “查看当前每日论文配置”, or first-run setup."
        ),
        workflow="workflows/configure.md",
        resources=COMMON_CONFIG
        + CONFIG_GUARD
        + (
            "scripts/shared/run_context.py",
            "scripts/shared/vault_coordination.py",
        ),
    ),
)


def _skill_markdown(skill: PublicSkill) -> bytes:
    workflow = (SUITE_ROOT / skill.workflow).read_text(encoding="utf-8")
    header = (
        "---\n"
        f"name: {skill.name}\n"
        "description: |\n"
        + "\n".join(
            f"  {line}" for line in _wrap_description(skill.description)
        )
        + "\n---\n\n"
        "<!-- Generated by tools/sync_public_skills.py; edit the canonical "
        "workflow in skills/daily-papers. -->\n\n"
    )
    return (header + workflow).encode("utf-8")


def _wrap_description(value: str, width: int = 78) -> list[str]:
    words = value.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if current and len(candidate) > width:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return lines


def _expected_files(skill: PublicSkill) -> dict[Path, bytes]:
    expected = {Path("SKILL.md"): _skill_markdown(skill)}
    for relative in skill.resources:
        expected[Path(relative)] = (SUITE_ROOT / relative).read_bytes()
    return expected


def sync(*, check: bool) -> list[str]:
    problems: list[str] = []
    for skill in PUBLIC_SKILLS:
        target_root = SKILLS_ROOT / skill.name
        expected = _expected_files(skill)
        for relative, content in expected.items():
            target = target_root / relative
            if check:
                if not target.exists():
                    problems.append(f"missing: {target.relative_to(REPO_ROOT)}")
                elif target.read_bytes() != content:
                    problems.append(f"stale: {target.relative_to(REPO_ROOT)}")
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)

        if check and target_root.exists():
            actual = {
                path.relative_to(target_root)
                for path in target_root.rglob("*")
                if path.is_file() and "__pycache__" not in path.parts
            }
            extras = actual - set(expected)
            problems.extend(
                f"unexpected: {(target_root / path).relative_to(REPO_ROOT)}"
                for path in sorted(extras)
            )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    problems = sync(check=args.check)
    if problems:
        print("\n".join(problems), file=sys.stderr)
        return 1
    if not args.check:
        print(
            "Synced public skills: "
            + ", ".join(skill.name for skill in PUBLIC_SKILLS)
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
